### ISSUE TITLE
attached / grouped team improvements

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#310]
If we want the program to 'remember' groupings (i.e. create a grouping on the first 'with' message, and keep the teams grouped until the radio operator takes some action to ungroup them) there are a few UI considerations:
1. make it highly visible in the main window: move grouped team tabs to be adjacent to each other, and draw a big bold box around the group?
2. make it highly visible in the new entry dialog
3. make it easy to ungroup from the main window
4. make it easy to ungroup from NED

**Comment by caver456** [comment]
changed to high priority bug - was causing lots of problems and crashes probably due to bad parsing on the Pennington search 4-6-17

**Comment by caver456** [comment]
Looks like amending an attached message screws it up.  Will debug this at a later date; will just disable team attachments for now (disable the GUI field, and either disable the action that creates attached messages, or, make sure attachedCallsign is empty)

7346:newEntry called with these values:
7346:['1908', 'FROM', 'Team ic', 'asdfasdf with other stuff', None, '', 1491617326.4349856, None, None, None]
7346:new team: newTeamName=Team ic extTeamName=z_Team ic niceTeamName=Team ic shortNiceTeamName=ic
7346:attached callsigns: ['other', 'stuff']
7346:newEntry called with these values:
7346:['1908', 'FROM', 'other', '[ATTACHED FROM Team ic] asdfasdf with other stuff', None, '', 1491617326.4349856, None, None, None]
7346:new team: newTeamName=other extTeamName=z_other niceTeamName=other shortNiceTeamName=other
7346:newEntry called with these values:
7346:['1908', 'FROM', 'stuff', '[ATTACHED FROM Team ic] asdfasdf with other stuff', None, '', 1491617326.4349856, None, None, None]
7346:new team: newTeamName=stuff extTeamName=z_stuff niceTeamName=stuff shortNiceTeamName=stuff
7346:Accepted2
7346:removeTab: count=3 i=1
7346:tabCount=2 currentIndex=1
7346:tabCount=2 currentIndex=1
7346:lowering: count=3
7346:closed
7354:row:3:['1908', 'FROM', 'stuff', '[ATTACHED FROM Team ic] asdfasdf with other stuff', '', '', 1491617326.4349856, None, None, None]
7355:Amending row 3
7355:newEntryWidget created
7355:tabCount=3 currentIndex=1
7355:tabCount=3 currentIndex=1
7355:clueLog.openDialogCount=0
7355:changeCallsignDialog.openDialogCount=0
7355:subjectLocatedDialog.openDialogCount=0
7355:showing
7355:raising
7363:resetting last mod age for stuff
...
7369:Accepted
7369:attached callsigns: ['other', 'stuff']
7369:newEntry called with these values:
7369:['1908', 'FROM', 'other', '[ATTACHED FROM stuff] new stuff [ATTACHED FROM Team ic] asdfasdf with other stuff', '', '', '1908', None, None, None]
7369:newEntry called with these values:
7369:['1908', 'FROM', 'stuff', '[ATTACHED FROM stuff] new stuff [ATTACHED FROM Team ic] asdfasdf with other stuff', '', '', '1908', None, None, None]
7369:Accepted2
7369:removeTab: count=3 i=1
7369:tabCount=2 currentIndex=1
7369:tabCount=2 currentIndex=1
7369:lowering: count=3
7369:closed
Traceback (most recent call last):
  File "radiolog.py", line 2045, in <lambda>
    QTimer.singleShot(100,lambda:self.newEntryPost(extTeamName))
  File "radiolog.py", line 2050, in newEntryPost
    self.radioLog.sort(key=lambda entry: entry[6]) # sort by epoch seconds - in case dialogs are accepted out of order
TypeError: unorderable types: str() < float()

**Comment by caver456** [comment]
changing back to med priority enhancement per the notes above
