### ISSUE TITLE
crash: addentry throb on already-closed dialog

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#333]
Crash #2: quick-succession closing of NEDs - throb isn’t called until after object is already deleted

94.7:76.6 9143:removeTab: count=6 i=4
94.7:76.6 9143:tabCount=5 currentIndex=4
94.7:76.6 9143:tabCount=5 currentIndex=3
94.7:76.6 9143:tabCount=5 currentIndex=3
94.7:76.6 9143:closed
94.7:76.6 9143:removeTab: count=5 i=3
94.7:76.6 9143:tabCount=4 currentIndex=3
94.7:76.6 9143:tabCount=4 currentIndex=2
94.7:76.6 9143:tabCount=4 currentIndex=2
94.7:76.6 9143:closed
Traceback (most recent call last):
  File "radiolog.py", line 2937, in <lambda>
    QTimer.singleShot(15,lambda:self.throb(n+1))
  File "radiolog.py", line 2935, in throb
    self.setPalette(self.palette)
RuntimeError: wrapped C/C++ object of type newEntryWidget has been deleted

Solution: make throb smarter to only run if parent still exists??

see 'radiolog crashes' google doc for the latest:
https://docs.google.com/document/d/1aaT7luzb8SpeVSSoEr_CXXrV_LwvUgE0ANxw2iYaokM/edit?usp=sharing

**Comment by caver456** [comment]
see related notes in http://stackoverflow.com/questions/21079941 - need to make the timer a normal timer then use setSingleShot so we can call .stop() from .closeEvent
