### ISSUE TITLE
usb hot plug / unplug

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#41]
deal gracefully with USB hot plug / unplug

**Comment by caver456** [comment]
Looked at the transcript when unplugging USB while radiolog is running in the trailer.  Repeated error messages (every second):
```
Traceback (most recent call last):
  File "radiolog.py", line 714, in fsCheck
    if self.firstComPortFound and self.firstComPort.inWaiting():
  File "C:\Python34\lib\site-packages\serial\serialwin32.py", line 239, in inWaiting
    raise SerialException('call to ClearCommError failed')
serial.serialutil.SerialException: call to ClearCommError failed
```

**Comment by caver456** [comment]
free virtual serial ports don't accurately mimic a hot plug / unplug; will need to try in the trailer:
just try this - note that inWaiting() was changed to a property in pySerial 3.0:
if self.firstComPortFound:
   if firstComPort.is_open:
      if self.firstComPort.inWaiting():
         self.fsBuffer=...
   else:
      self.firstComPortFound=False

**Comment by caver456** [comment]
isOpen() is not sufficient - the port stays open even after hot unplug; use 'try .. except serial.serialutil.SerialException instead

**Comment by caver456** [comment]
hot-plug was already working before this issue report, but note that it takes 5 seconds or so for radiolog to recognize the port, after the windows chime.

**Comment by caver456** [comment]
noticed in Feb 2019 that hot-unplug is no longer working, i.e. the ports never get freed, therefore when they are plugged back in they don't get recognized anew.  Reopening.

**Comment by caver456** [comment]
Looks like this was a change in pyserial between then and now.  The current error message upon unplug is:
`ClearCommError failed (PermissionError(13, 'The device does not recognize the command.', None, 22))`
since the text 'ClearCommError failed' exists in both versions, the plan is to just match against that regex.

**Comment by caver456** [comment]
also ran into some logic issues where the lights aren't turned off on unplug of a non-radio com device; basically looks like the validity of data is not checked before turning on the lights and setting first/secondComPortAlive.  The logic around line 1227 should be improved.  But that is probably a separate issue since the logic at lines 1259 etc should work for actual radios.  So, committing and closing this change.
