### ISSUE TITLE
multiple crashes June 2 2020

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#413]
Craig gave good detail on four crashes.  Auto-recover worked each time, but fleetsync pairings had to be re-entered each time, see separate issue for that enhancement.  Craig reported no apparent reason or pattern.  Crashes were immediate (not after a lag).

Log files show a possible pattern: last lines in 3 of the 4 crash logs were right after incoming CID, all on radios that had been giving GPS WARNINGs on some calls (need to check how often).

Steve got the log files from the trailer.

Search name was "Hoyt's" - wondering if the apostrophe was related.

Steve had installed the shared-drive remount script recently.  Should check system logs.

First log file (105241): last lines in log (113603) seem like a clean file write after a 'departing ic' entry.  No tracebacks or other visible issues in the log file.  GPS mic warnings for device IDs 2019, 2014, 2013.  Log entry just before crash was GPS with warning from 2013.  Accepted team name (half a minute after incoming GPS?) was 'Radio 101' indicating that change callsign dialog wasn't working or wasn't being used.

Second log file (113649): last line in log (125707) is 'CID detected (not in $PKLSH): fleet=100 dev=2019 callsign=Team 102' - seems normal - incoming CID.  This device was previously sending GPS also, so crash could have been on incoming GPS data before log was written.  GPS WARNINGs from 2019,2014,2013,2005

Third log file (125736): last line in log (155837) is 'CID detected (not in $PKLSH): fleet=100 dev=2014 callsign=Team 101 - seems normal - incoming CID.  This device was previously sending GPS.  Same as above - crash could have been on incoming GPS data before log was written.  GPS WARNINGS from 2019,2014,2013,2005,2001,2003.  *LOTS of non-fatal  tracebacks during every coordinate parsing call, e.g.:
```131026:PARSING
131026:17.9701,N,12105.0319,W,,,,,*00
$GPGGA,201030,3917.9701,N,12105.0319,W,1,,,,,,,,*41
131026: line:17.9701,N,12105.0319,W,,,,,*00
131026: line:$GPGGA,201030,3917.9701,N,12105.0319,W,1,,,,,,,,*41
131026: line:
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 1307, in fsCheck
    self.fsParse()
  File "radiolog.py", line 1423, in fsParse
    self.fsLogUpdate(int(fleet),int(dev))
UnboundLocalError: local variable 'fleet' referenced before assignment
```

Fourth log file (155858): last line (163729) is 'CID detected (not in $PKLSH): fleet=100 dev=2003 callsign=Team 106'.  gps WARNINGs from 2019,2014,2013,2005.  Lots of the same tracebacks as third log file.

Fifth log file (163743): GPS WARNINGs from 2019,2014,2013,2005.  No tracebacks.  Why??  Clean print and shutdown.

**Comment by caver456** [comment]
just noticed that no 'returned from get request' appears in the logs (#404).  Should investigate, but, probably not directly related since the terminating incoming FS was CID-only (beginning of transmission) in crashes 2,3,4.

**Comment by caver456** [comment]
added more logging; enhanced fsTester to send WARNING ('V') but could not duplicate the crashes at home.  Will need to check system logs in the trailer.

**Comment by caver456** [comment]
Closing, because:
- haven't heard any similar reports or seen any similar issues in over 2 years
- the entire code section that includes the self.fsLogUpdate warnings above has been wrapped in 'if fleet and dev:' since Jun 16 2020 which may have resolved the issue
- any of the other code changes made since the original crashes could have resolved the issue
