### ISSUE TITLE
Crash after cancelling a clue entry

### ISSUE THREAD

**Issue by SAR85** [ncssar/radiolog#456]
Radiolog hangs then crashes after cancelling a clue entry, then won't start again from the same installation folder. The following message is displayed when trying to re-open the program:

`[ INFO ] Operating system is Windows.
[ INFO ] PowerShell.exe is in the path.
[ INFO ] Operating system is Windows.
[ INFO ] PowerShell.exe is in the path.
[ WARNING ] Cannot read FleetSync ID table file 'radiolog_fleetsync.csv' and no FleetSync ID table has yet been loaded.  Callsigns for incoming FleetSync calls will be of the format 'KW-<fleet>-<device>'.
Traceback (most recent call last):
  File "radiolog.py", line 2656, in <module>
  File "radiolog.py", line 2644, in main
  File "radiolog.py", line 481, in __init__
AttributeError: 'Namespace' object has no attribute 'first_time_install'
[13680] Failed to execute script radiolog`

Re-installing allows the program to run again.

**Comment by caver456** [comment]
see #455 - let's leave this open, thanks for the detailed report!
