### ISSUE TITLE
clicking LOCATED A CLUE during amend leaves window stuck open, leaving radiolog unusable

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#462]
To reproduce:
1. add any entry
2. amend that entry
3. click 'LOCATED A CLUE'

The simple traceback this causes results in a new entry window that cannot be closed, because it complains that a clue dialog is open (which is not true) and must be closed first.

```
054941:Amending row 1
054941:openNewEntry called:key=None callsign=None formattedLocString=None fleet=None dev=None origLocString=None amendFlag=True amendRow=1
054943:False
054943:newEntry called with these values:
054943:['0548', 'FROM', 'Team 101', "RADIO LOG SOFTWARE: 'LOCATED A CLUE' button pressed; radio operator is gathering details", '', '', '0548', None, None, None]
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 4781, in quickTextClueAction
    self.newClueDialog=clueDialog(self,self.ui.timeField.text(),self.ui.teamField.text(),self.ui.radioLocField.toPlainText(),lastClueNumber+1)
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 5339, in __init__
    self.parent.parent.newEntry(self.values)
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 3141, in newEntry
    while i>-1 and sec<self.radioLog[i][6]:
TypeError: '<' not supported between instances of 'str' and 'float'
```

**Comment by caver456** [comment]
The underlying cause was incorrect array parsing in newEntryWidget.__init__ setting self.sec to the 24hr time string, rather than the timestamp:

```
if amendFlag:
	row=parent.radioLog[amendRow]
	self.sec=row[0]
	self.formattedLocString=row[4]
```

changed to

```
if amendFlag:
	row=parent.radioLog[amendRow]
	self.sec=row[6]
	self.formattedLocString=row[4]
```


where a row looks like this:
`['0650', 'FROM', 'Team 102', 'RADIO CHECK: OK', '', '', 1654609814.4134073, None, None, None]`


Also, added a safety check on the line that caused the exception, to make sure the value being compared is a float.

This showed a related issue that the radio log will have the informational entry >after< the amended entry, which looks confusing:

![image](https://user-images.githubusercontent.com/18752102/172400563-3a49ae95-d7c6-488c-bc8e-d495d96a97be.png)

Considering a few possible ways to clean that up:
- move the informational message to just before the amended message
- don't show the informational message when done during amend
- add text 'during amend of previous message' when done during amend

Probably the least impactful and clearest option is the third one - add text when done during amend.  Make sure to include the word 'previous' to avoid confusing when this message appears below the amended message.
