### ISSUE TITLE
RuntimeError when new entry widget is closed before change callsign dialog can open

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#482]
On a new incoming fleetsync call, a new entry widget is opened in the new entry dialog.  If escape (or cancel) is pressed >>reeely fast<< before the change callsign dialog can open (500ms singleshot), openChangeCallsignDialog throws this non-blocking non-fatal exception; the user experience is as-expected, everything continues normally; the only actual problem is these lines in the log file:

Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 3220, in <lambda>
    QTimer.singleShot(500,lambda:self.newEntryWidget.openChangeCallsignDialog())
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 4940, in openChangeCallsignDialog
    self.changeCallsignDialog=changeCallsignDialog(self,self.ui.teamField.text(),self.fleet,self.dev)
RuntimeError: wrapped C/C++ object of type QLineEdit has been deleted

It would be best to clean these up.  Could try passing the teamFieldText as an argument, or only opening the dialog if the new entry widget is still open, etc.

**Comment by caver456** [comment]
decided on a minimal fix here (wrap in try/except) since the error is completely not a real problem.
