### ISSUE TITLE
IndexError exception during pdf generation

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#523]
Hopefully this one is easy to figure out.

From the user:

"Radiolog err on exit with print at 1328 (did not print).  Then restarted radiolog and prints ok; but logs output (and the messages in the log file) says op, and there was no clue log printed. Reprint of clue log only worked; it says op4."

```
132352:PRINT radio log
132352:teamFilterList=['']
132352:generating radio log pdf: C:\Users\NCSSAR\Documents\Bridgeport_2022_09_24_081953_OP4.pdf
Uncaught exception
Traceback (most recent call last):
  File "C:\radiolog-3p0p1b\radiolog-master\radiolog.py", line 4501, in accept
    self.parent.printLog(opPeriod)
  File "C:\radiolog-3p0p1b\radiolog-master\radiolog.py", line 2271, in printLog
    radioLogPrint[1][4]=self.datum
IndexError: list index out of range
```

From the subsequent radiolog session, note the filename includes 'OP1':

```
132840:PRINT radio log
132840:teamFilterList=['']
132840:generating radio log pdf: C:\Users\NCSSAR\Documents\Bridgeport_2022_09_24_132831_OP1.pdf
132840:length:134
132840:valid logo file ./local/radiolog_logo.jpg
132840:Page number:1
132840:Height:43.199999999999996
132840:Pagesize:(792.0, 612.0)
132840:done drawing printLogHeaderFooter canvas
132840:end of printLogHeaderFooter
132840:valid logo file ./local/radiolog_logo.jpg
132840:Page number:2
132840:Height:43.199999999999996
132840:Pagesize:(792.0, 612.0)
132840:done drawing printLogHeaderFooter canvas
132840:end of printLogHeaderFooter
132840:valid logo file ./local/radiolog_logo.jpg
132840:Page number:3
132840:Height:43.199999999999996
132840:Pagesize:(792.0, 612.0)
132840:done drawing printLogHeaderFooter canvas
132840:end of printLogHeaderFooter
132840:valid logo file ./local/radiolog_logo.jpg
132840:Page number:4
132840:Height:43.199999999999996
132840:Pagesize:(792.0, 612.0)
132840:done drawing printLogHeaderFooter canvas
132840:end of printLogHeaderFooter
132840:valid logo file ./local/radiolog_logo.jpg
132840:Page number:5
132840:Height:43.199999999999996
132840:Pagesize:(792.0, 612.0)
132840:done drawing printLogHeaderFooter canvas
132840:end of printLogHeaderFooter
132840:valid logo file ./local/radiolog_logo.jpg
132840:Page number:6
132840:Height:43.199999999999996
132840:Pagesize:(792.0, 612.0)
132840:done drawing printLogHeaderFooter 
```

**Comment by caver456** [comment]
From the log and the code, clearly it's generating the pdf for OP4:

`132352:generating radio log pdf: C:\Users\NCSSAR\Documents\Bridgeport_2022_09_24_081953_OP4.pdf`

```
		pdfName=pdfName.replace('.pdf','_OP'+str(opPeriod)+'.pdf')
		rprint("generating radio log pdf: "+pdfName)
```

But, how did it get to be OP4??

There should only be three ways that the OP could be set - but the transcript shows no indication of these:
1) GUI
2) load a previous session (F4)
3) auto-restore a previous session after unclean shutdown


1 - Changing the OP from the GUI would create a new entry like so (just reconfirmed by testing):

```
061729:newEntry called with these values:
061729:['0617', '', '', 'Operational Period 2 Begins: Mon Oct 10, 2022', '', '', 1665407849.5496066, '', '']
```

But there are no such entries in the log file or the transcript.

2 - Loading a previous session would create a transcript entry like so (taken from the subsequent radiolog session from the initial report):

132825:Loading:C:/Users/NCSSAR/Documents/Bridgeport_2022_09_24_081953.csv

3 - Auto-restore also creates the 'Loading' line as above.

--> Found it, and verified in a test: the OP can be set by clicking YES in the continued incident dialog, which does result in an entry like this in the log, but, does not generate any indication in the transcript:

`Radio Log Begins - Continued incident "New Incident": Operational Period 3 Begins: Mon Oct 10, 2022`

So - make a new issue: add transcript indication when continued incident is accepted; generally, add transcript indication when 'radio log begins' line is generated, since newEntry() is not called (and therefore no new radiolog csv is saved solely due to this action).

**Comment by caver456** [comment]
Was able to reproduce in the same scenario as #525: start a session, answer YES in the continued incident dialog, then print from the print button in the main GUI, without having made any new entries.

**Comment by caver456** [comment]
While this exception may be triggered by the same problems that trigger #525, wrapping the line in a try/except clause, returning from the function if there is nothing to print, will also fix this issue more directly.

**Comment by caver456** [comment]
The try/except prevents the exception, but, the 'except' clause is still getting triggered.  In other words, there is nothing to print.  Why??
