### ISSUE TITLE
executable: failure to automatically print clue report when accepting clue dialog

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#536]
The dialog doesn't close, and this shows in the transcript:

```
150835:generating clue report pdf: C:\Users\caver\Documents\New_Incident_2022_10_16_141531_clue01.pdf
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 5857, in accept
  File "radiolog.py", line 2658, in printClueReport
  File "PyPDF2\_reader.py", line 1944, in __init__
  File "PyPDF2\_reader.py", line 315, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'clueReport.pdf'
```

Canceling the clue dialog does work, but, the clue data is lost.

**Comment by caver456** [comment]
As a hotfix, copying clueReport.pdf to the install dir (C:\Users\<user>\AppData\Local\Programs\radiolog) does work, and the next clue report generates correctly.

This might be an issue with the release workflow - probably a list of what files to include in the build is just missing clueReport.pdf.  Still - probably worth a patch release (3.1.1).

**Comment by caver456** [comment]
Just to be clear, this was found while going through the checklist in #474 - that list is something I should have done a few months back when @erinn first rolled out the release workflow.

**Comment by caver456** [comment]
Guessing this goes in 'datas' in the pyinstaller spec file radiolog.spec.

**Comment by caver456** [comment]
That does work - clueReport.pdf shows up in the dist dir after pyinstaller.

**Comment by caver456** [comment]
confirmed that it does print a clue report correctly from a fresh install of 3.1.1.
