### ISSUE TITLE
deal with loaded files that didn't use operator login, in a session where operator login is enabled

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#637]
This clause can give a IndexError, if useOperatorLogin is true, but row[11] doesn't exist (v3.5.0 line 2685 in printLog, but, there may be more):

```
if self.useOperatorLogin:
	printRow.append(row[10])
```

The result is that the log will not print.  Immediate solution should be to change the config file to disable operator login flow, then restart and reload.

**Comment by caver456** [comment]
The errors in v3.5.0:

If there are any clues to print:

```
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 5290, in accept
  File "radiolog.py", line 2830, in printClueLog
IndexError: list index out of range
```

During print of the entire log or of team logs:

```
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 5283, in accept
  File "radiolog.py", line 2685, in printLog
IndexError: list index out of range
```

**Comment by caver456** [comment]
Related - also falls under this issue: when loading a radiolog that didn't use operator login, operator appears as the currently logged in operator for all loaded entries.  Don't do that.  The operator field for loaded entries should stay blank if that loaded file didn't use operator login.
