### ISSUE TITLE
clue dialog closure errors

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#651]
Unusual entries and dialog closure issues when accepting a clue dialog, noticed in 3.6.1 on 5-21-23:

![20230521_150840](https://github.com/ncssar/radiolog/assets/18752102/7806fbfb-4982-4fa2-9582-daf003368361)

Accompanied by these lines in the log file:

```
134632:newEntry called with these values:
134632:['1343', 'FROM', 'Team 101', 'RADIO LOG SOFTWARE: CLUE REPORT OPENED BUT CANCELED BY THE OPERATOR.  CLUE REPORT DATA BEFORE CANCELATION: DESCRIPTION="fake cardboard bloody knife" LOCATION="92861 53231" INSTRUCTIONS="MARK & LEAVE; PHOTOGRAPH; CONTINUE SEARCH" ', '92864  53237', 'Working', 1684701806.231355, '100', '3035', '3918.4232|N|12045.7882|W']
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 6924, in closeEvent
ValueError: list.remove(x): x not in list
```

Other occurrences have more error lines - it looks like this problem was plaguing the operators all day:

```
112745:generating clue report pdf: C:\Users\NCSSAR\RadioLog\Chalk_Bluff_2023_05_21_081803\Chalk_Bluff_2023_05_21_081803_clue01.pdf
112748:accepted - calling close
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 6871, in accept
  File "radiolog.py", line 6924, in closeEvent
ValueError: list.remove(x): x not in list
112755:Accepted
112755:newEntry called with these values:
112755:['1125', 'FROM', 'Team 103', 'CLUE#1: 1X1 BLUE MATERIAL, RIP STOP IN DEEP BRUSH ; LOCATION: 92670 X 53305; INSTRUCTIONS: MRK ON GPS AND PROCEED W/ASSIGNMENT; CLUE#1: 1X1 BLUE MATERIAL, RIP STOP IN DEEP BRUSH ; LOCATION: 92670 X 53305; INSTRUCTIONS: MRK ON GPS AND PROCEED W/ASSIGNMENT', '92662  53299', 'Working', 1684693522.5658386, '100', '4007', '3918.4596|N|12045.9276|W']
112755:Accepted2
112755:  writing C:\Users\NCSSAR\RadioLog\Chalk_Bluff_2023_05_21_081803\Chalk_Bluff_2023_05_21_081803.csv
112755:  done writing C:\Users\NCSSAR\RadioLog\Chalk_Bluff_2023_05_21_081803\Chalk_Bluff_2023_05_21_081803.csv
112755:  writing X:\Chalk_Bluff_2023_05_21_081803.csv
112755:  done writing X:\Chalk_Bluff_2023_05_21_081803.csv
112755:  writing C:\Users\NCSSAR\RadioLog\Chalk_Bluff_2023_05_21_081803\Chalk_Bluff_2023_05_21_081803_clueLog.csv
112755:  done writing C:\Users\NCSSAR\RadioLog\Chalk_Bluff_2023_05_21_081803\Chalk_Bluff_2023_05_21_081803_clueLog.csv
112755:  writing X:\Chalk_Bluff_2023_05_21_081803_clueLog.csv
112756:  done writing X:\Chalk_Bluff_2023_05_21_081803_clueLog.csv
112813:vText:
112813:generating clue report pdf: C:\Users\NCSSAR\RadioLog\Chalk_Bluff_2023_05_21_081803\Chalk_Bluff_2023_05_21_081803_clue01.pdf
112813:parsed instructions:['mrk on gps and proceed w/assignment']
112813:copying clue report pdf to X:\
112813:accepted - calling close
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 6871, in accept
  File "radiolog.py", line 6924, in closeEvent
ValueError: list.remove(x): x not in list
112814:vText:
112814:generating clue report pdf: C:\Users\NCSSAR\RadioLog\Chalk_Bluff_2023_05_21_081803\Chalk_Bluff_2023_05_21_081803_clue01.pdf
112818:accepted - calling close
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 6871, in accept
  File "radiolog.py", line 6924, in closeEvent
ValueError: list.remove(x): x not in list
112843:vText:
112843:generating clue report pdf: C:\Users\NCSSAR\RadioLog\Chalk_Bluff_2023_05_21_081803\Chalk_Bluff_2023_05_21_081803_clue01.pdf
112843:parsed instructions:['mrk on gps and proceed w/assignment']
112843:copying clue report pdf to X:\
112843:accepted - calling close
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 6871, in accept
  File "radiolog.py", line 6924, in closeEvent
ValueError: list.remove(x): x not in list
112844:vText:
112844:generating clue report pdf: C:\Users\NCSSAR\RadioLog\Chalk_Bluff_2023_05_21_081803\Chalk_Bluff_2023_05_21_081803_clue01.pdf
112854:accepted - calling close
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 6871, in accept
  File "radiolog.py", line 6924, in closeEvent
ValueError: list.remove(x): x not in list
112907:newEntry called with these values:
112907:['1125', 'FROM', 'Team 103', 'RADIO LOG SOFTWARE: CLUE REPORT OPENED BUT CANCELED BY THE OPERATOR.  CLUE REPORT DATA BEFORE CANCELATION: DESCRIPTION="1X1 BLUE MATERIAL, RIP STOP IN DEEP BRUSH " LOCATION="92670 X 53305" INSTRUCTIONS="MRK ON GPS AND PROCEED W/ASSIGNMENT" ', '92662  53299', 'Working', 1684693522.5658386, '100', '4007', '3918.4596|N|12045.9276|W']
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 6924, in closeEvent
ValueError: list.remove(x): x not in list
```

**Comment by caver456** [comment]
bingo - the theory was right - the error during rotate causes the dialog to be left open; hitting OK again triggers the error pair line.

So this should be a two-part solution:
1) solve #650 so that an error in the backup script doesn't leave the clue dialog open;
2) check for existence of self in self.parent.childDialogs before removing, to prevent the error lines in question - though this is mainly cosmetic

**Comment by caver456** [comment]
for reference: the error was duplicated by setting rotateScript='' in radiolog.cfg, then adding a clue as the 5th saved entry so that the rotate script was called during accept of the clue dialog.
