### ISSUE TITLE
3.11.0 does not run due to pygeodesy missing attributes

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#723]
First noticed on R5.  Can duplicate the problem on the installed executable at home.  Removed release 3.11.0.

```
PS C:\Program Files (x86)\RadioLog> .\radiolog.exe
Traceback (most recent call last):
  File "radiolog.py", line 333, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pygeodesy\__init__.py", line 585, in <module>
  File "pygeodesy\__init__.py", line 573, in _all
ImportError: missing attributes[2]: pygeodesy.rhumb.RhumbAux, pygeodesy.rhumb.RhumbLineAux
[23696] Failed to execute script 'radiolog' due to unhandled exception!
PS C:\Program Files (x86)\RadioLog>
```

**Comment by caver456** [comment]
Interesting google hit:

https://mrjean1.github.io/PyGeodesy/
`"[pygeodesy.deprecated.rhumbaux](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.deprecated.rhumbaux-module.html): DEPRECATED on 2023.11.26, use module [pygeodesy.rhumb.aux_](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.rhumb.aux_-module.html) instead."`

There is a pygeodesy version difference between the built release and the dev code.

'pip list' shows PyGeodesy 23.11.11 but the github action log for the 3.11.0 build shows pygeodesy-23.12.23.

One option would be to hardcode 23.11.11 in requirements.txt.  Should keep digging first...

**Comment by caver456** [comment]
Upgrading pygeodesy in the dev machine to 23.12.23 does not trigger the error.   So, it seems like maybe it's more similar to [this closed ticket from 2019](https://github.com/mrJean1/PyGeodesy/issues/31)

Will still try hardcoding the pygeodesy version number in requirements.txt and rebuilding a test release.  What other change could have caused 3.10.2 to work but 3.11.0 to fail?

**Comment by caver456** [comment]
Hardcoding geodesy in requirements.txt does allow the built installation to run correctly.  Confirmed with another user.  Will open an issue on the pygeodesy project, but, this particular issue is fixed.
