### ISSUE TITLE
failure to delete team tab 'Team 101 Back Up'

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#728]
Reported in #727.

```
102542:deleteTeamTabAction clicked
102542:deleting team tab: teamName=Team 101BackUp  extTeamName=z_Team101BackUp  niceTeamName=Team 101backUp
102542:  teamNameList before deletion:['dummy', 'Team 101', 'Team 102', 'Team 103', 'Team 104', 'Team 101BackUp']
102542:  extTeamNameList before deletion:['spacerLeft', 'z_Team00101', 'z_Team00102', 'z_Team00103', 'z_Team00104', 'z_Team101BackUp', 'spacer1']
102542:  i=5
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 5369, in tabContextMenu
  File "radiolog.py", line 5840, in deleteTeamTab
ValueError: list.remove(x): x not in list
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 3831, in updateTeamTimers
ValueError: 'z_Team101BackUp' is not in list
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 3831, in updateTeamTimers
ValueError: 'z_Team101BackUp' is not in list
...
...
```

the not-in-list valueerror repeats every second for the rest of the session.
This is the code in question.  Seems like this error should never happen...?

```
		if extTeamName in self.extTeamNameList: # pass through if trying to delete a tab that doesn't exist / has already been deleted
			i=self.extTeamNameList.index(extTeamName)
			rprint("  i="+str(i))
			self.extTeamNameList.remove(extTeamName)
```

**Comment by caver456** [comment]
was able to reproduce the issue using the same team name 'team 101 back up', both when that was the first/only tab, and when it was not the first/only tab.  Tried a more standard team name with no spaces, and was able to delete that tab with no errors.

Guessing this is due to having a space (actually, two spaces) in the team name.   Need to track down exactly why.  Space(s) in team names should be allowed, though a bit odd.

**Comment by caver456** [comment]
Fresh test with current line numbers:

```
073235:deleteTeamTabAction clicked
073235:deleting team tab: teamName=Team 101BackUp  extTeamName=z_Team101BackUp  niceTeamName=Team 101backUp
073235:  teamNameList before deletion:['dummy', 'Team 101BackUp']
073235:  extTeamNameList before deletion:['spacerLeft', 'z_Team101BackUp', 'spacer1']
073235:  i=1
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 5581, in tabContextMenu
    self.deleteTeamTab(niceTeamName)
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 6052, in deleteTeamTab
    self.teamNameList.remove(niceTeamName)
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 4004, in updateTeamTimers
    i=self.extTeamNameList.index(extTeamName)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'z_Team101BackUp' is not in list
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 4004, in updateTeamTimers
    i=self.extTeamNameList.index(extTeamName)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'z_Team101BackUp' is not in list
...
```

Line 6052 in deleteTeamTab - this only happens once:

`				self.teamNameList.remove(niceTeamName)`

True, "Team 101backUp" is not in ['dummy', 'Team 101BackUp'].


Lines leading up to and including 4004 in updateTeamTimers (I culled to much stuff from the snippett in the previous comment) - this gets called once every second:

```
		for extTeamName in teamTimersDict:
			secondsSinceContact=teamTimersDict.get(extTeamName,0)
			if extTeamName not in self.hiddenTeamTabsList:
				# rprint('updateTeamTimers processing '+extTeamName)
				# if there is a newEntryWidget currently open for this team, don't blink,
				#  but don't reset the timer.  Only reset the timer when the dialog is accepted.
				hold=False
				for widget in newEntryWidget.instances:
					if widget.ui.to_fromField.currentText()=="FROM" and getExtTeamName(widget.ui.teamField.text())==extTeamName:
						hold=True
				i=self.extTeamNameList.index(extTeamName)
```

Hiding a 'normal' team shows that this error is happening because the team was never added to hiddenTeamTabsList, due to the early exit from deleteTeamTab due to the first error.

To prevent recurring tracebacks, it's probably best to wrap 4004 in 'if extTeamName in self.extTeamNameList'.  There's no great harm that comes from the 'malformed' team not being blinked/etc.  But steps should be taken to prevent this from happening:

Seems like there are two options:
1) rework the capitalization-and-space logic be reworked to allow for team names with multiple spaces
 OR
2) disallow team names with multiple spaces and show some warning or error when there's an attempt to create such a team

1) seems a bit silly but might be less invasive and a 'better' solution.  Pondering...

**Comment by caver456** [comment]
Thinking that option 2, but without any visual warning, is the way to go: in teamFieldEditingFinished, automatically get rid of any spaces after the first.  Shouldn't be that hard...

On accept of the first message from 'Team 101 back up', things look OK:

```
062121:Accepted
062121:newEntry called with these values:
062121:['0621', 'FROM', 'Team 101 back up', 'STARTING ASSIGNMENT', None, 'Working', 1726924877.9727244, None, None, None]
062121:new team: newTeamName=Team 101 back up extTeamName=z_Team101BackUp niceTeamName=Team 101BackUp shortNiceTeamName=101BackUp
```

niceTeamName during the attempt to delete the tab doesn't match niceTeamName from the first accept:

```
062125:deleting team tab: teamName=Team 101BackUp  extTeamName=z_Team101BackUp  niceTeamName=Team 101backUp
062125:  teamNameList before deletion:['dummy', 'Team 101BackUp']
062125:  extTeamNameList before deletion:['spacerLeft', 'z_Team101BackUp', 'spacer1']
```

**Comment by caver456** [comment]
This might be the smoking gun:

```
200942:getExtTeamName called with argument "Team 101 back up"
200942:Team Name:Team 101 Back Up: extended team name:z_Team101BackUp
...
200942:getExtTeamName called with argument "Team 101BackUp"
200942:Team Name:Team 101back Up: extended team name:z_Team101backUp
```

getExtTeamName capitalizes 'back' to 'Back' if preceded by a space, but lowercases 'Back' to 'back' when NOT preceded by a space.  It preserves the capital Up in both cases.

Also notice the second printed line of each call: in the first case, the space after 101 is preserved, and the B in back is capitalized (probably because it is after a space).  In the second case, there is no space after the 101, and (therefore?) the b in back is not capitalized.

Testing from the top for an entry from 'Team 101back up' (no space after 101), everything works as expected, because the lowercase b persists throughout, so is a match during tab deletion.  The problem with everything above is that the b is capitalized initially because it follows a space, but that uppercase is not preserved.

**Comment by caver456** [comment]
See #406; this is a touchy topic

**Comment by caver456** [comment]
The smoking gun:

```
>>> a='101back up'
>>> ' '.join(w.capitalize() for w in a.split())
'101back Up'
>>> a='101Back up' 
>>> ' '.join(w.capitalize() for w in a.split())
'101back Up'
>>>
```

So, capitalize apparently lowercases anything that's not the first letter of a word; we want to preserve case AND to capitalize the first letter of a word.

Others have had the same problem.  [This solution](https://stackoverflow.com/a/31767666/3577105) works nicely!

A test case with some other interesting callsigns shows a few other tracebacks - need to determine if they are related before closing and merging.

**Comment by caver456** [comment]
Looks like the tracebacks during testing are due to separate continued problems with hiding of back-to-back spacers, but, the behavior existed in 3.12.0 as well even though it was slightly different.  So - decision - go ahead and do a clean-up commit 9removal of excess prints and comments) then merge and close this issue, and create yet another issue for the back-to-back spacer problems during team tab hiding.
