### ISSUE TITLE
crash on restore - 'MyWindow' object has no attribute 'menuFontSize'

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#734]
Noticed in R6 3-2-24 and confirmed at home on a simple restore (answering 'yes' to the startup question that asks if you'd like to restore previous session after unclean shutdown):

```
085305:RadioLog 3.11.3
Working directory found at "C:\Users\caver\RadioLog".
Initial session directory created at "C:\Users\caver\RadioLog\NewSession_2024_03_03_085305".
085305:RadioLog 3.11.3
085306:opening findDialog
085306:Operating system is Windows.
085306:PowerShell.exe is in the path.
085306:updating options dialog: datum=WGS84
085306:Incident name changed to "New Incident".
085306:Renamed session directory to "C:\Users\caver\RadioLog\New_Incident_2024_03_03_085306"
085306:useOperatorLogin after readConfigFile:True
085306:updating options dialog: datum=WGS84
085306:Incident name changed to "New Incident".
085312:Initial entry: Restored after crash: Sun Mar 03, 2024
085312:Renamed session directory to "C:\Users\caver\RadioLog\New_Incident_2024_03_03_085312"
085312:loadOperators called
085312:Loading operator data from file C:\Users\caver\RadioLog\.config\radiolog_operators.json
085312:  loaded these operators:['Grundy,Tom']
085312:fsLoadLookup called: startupFlag=True  fsFileName=None  hideWarnings=False
085312:Loading FleetSync Lookup Table from file C:\Users\caver\RadioLog\.config\radiolog_fleetsync.csv
085312:Writing file C:\Users\caver\RadioLog\New_Incident_2024_03_03_085312\radiolog_fleetsync.csv
085312:Restoring previous session after unclean shutdown:
085312:Loading: C:\Users\caver\RadioLog\New_Incident_2024_03_03_085049\New_Incident_2024_03_03_085049.csv
085312:loaded incident name: 'New Incident'
085312:normalized loaded incident name: 'New_Incident'
085312:  t1 - done reading file
085312:newEntry called with these values:
085312:['0850', '', '', 'Restored after crash: Sun Mar 03, 2024', '', '', 1709484649.3054435, '', '', '', '']
085312:newEntry called with these values:
085312:['0852', 'FROM', 'Team 1', '20sadf', '', '', 1709484771.9411373, '', '', '', '??']
085312:new team: newTeamName=Team 1 extTeamName=z_Team00001 niceTeamName=Team 1 shortNiceTeamName=1
085312:extTeamNameList before sort:['dummy', 'z_Team00001']
085312:grouped tabs:{'NCSOcmd': [], 'NCSO': [], 'NCPD': [], 'TPD': [], 'GVPD': [], 'CHP': [], 'Numbers': ['z_Team00001'], 'other': ['dummy']}
085312:extTeamNameList after sort:['spacerLeft', 'z_Team00001', 'spacer1']
085312:next available hotkey:1
085312:loadTeamNotes called
085312:WARNING: Could not read team notes data file C:\Users\caver\RadioLog\New_Incident_2024_03_03_085049\team_notes.json
085312:  isfile: False
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 10123, in <module>
  File "radiolog.py", line 10116, in main
  File "radiolog.py", line 1331, in __init__
  File "radiolog.py", line 6135, in restore
  File "radiolog.py", line 4438, in load
  File "radiolog.py", line 4972, in rebuildTabs
  File "radiolog.py", line 5144, in addTab
AttributeError: 'MyWindow' object has no attribute 'menuFontSize'
```

**Comment by caver456** [comment]
easy fix - just do restore() after fontsChanged()
