### ISSUE TITLE
investigate reports of failure-to-recover

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#738]
R5 3.11.3, but could have been R6 3.11.4; reported at Spenceville 4/19/24 by Nancy; this seems like something that could have been fixed by 3.11.4, but need to look at transcripts to be sure

**Comment by caver456** [comment]
Looks like there were indeed three sessions showing the problem, during restore of a previous session due to unclean shutdown.  This was on R5, 3.11.3.  The run dirs were New_Incident_2024_04_18_[184459,184513,184609].  

In each case, here's the traceback during restore:

```
184609:WARNING: Could not read team notes data file C:\Users\NCSSAR\RadioLog\training_4_18_2024_04_18_183102\team_notes.json
184609:  isfile: False
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 10123, in <module>
  File "radiolog.py", line 10116, in main
  File "radiolog.py", line 1331, in __init__
  File "radiolog.py", line 6135, in restore
  File "radiolog.py", line 4438, in load
  File "radiolog.py", line 4972, in rebuildTabs
  File "radiolog.py", line 5144, in addTab
AttributeError: 'MyWindow' object has no attribute 'menuFontSize'
```
The main task now is to try to reproduce the error and hopefully confirm that it's already been fixed.

(In each case, the file that was being restored was C:\Users\NCSSAR\RadioLog\training_4_18_2024_04_18_183102\training_4_18_2024_04_18_183102.csv which ended after a file write at 184446, but there were no tracebacks - maybe the power was lost or such.  It's possible something in the file being restored could be the culprit, but seems unlikely.)
