### ISSUE TITLE
UnboundLocalError: local variable 'widget' referenced before assignment

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#748]
non-fatal and did not even notice this traceback - from the third session (auto-recovered) from R5 (3.11.5) during MRA mock at Donner Pass 20240817:

(this didn't show up in the first two sessions, which is probably just a coincidence; see #741 for the main problems that day)

```
135331:PARSING
135331:I110030181003018
135331: line:I110030181003018
135331:getCallsign called for FleetSync fleet=100 dev=3018
135331:  found matching entry/entries:[['100', '3018', 'Rescue 101']]
135331:FleetSync CID detected (not in $PKLSH): fleet=100  dev=3018  callsign=Rescue 101
135331:checking for existing open new entry tabs: callsign=Rescue 101 continueSec=20
135331:updating fsLog (fleetsync): fleet=100 dev=3018 callsign=<None>  COM port=COM3
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 2070, in fsCheck
  File "radiolog.py", line 2489, in fsParse
UnboundLocalError: local variable 'widget' referenced before assignment
135332:PARSING
135332:I110030181003018
135332: line:I110030181003018
135332:getCallsign called for FleetSync fleet=100 dev=3018
135332:  found matching entry/entries:[['100', '3018', 'Rescue 101']]
135332:FleetSync CID detected (not in $PKLSH): fleet=100  dev=3018  callsign=Rescue 101
135332:checking for existing open new entry tabs: callsign=Rescue 101 continueSec=20
135332:updating fsLog (fleetsync): fleet=100 dev=3018 callsign=<None>  COM port=COM3
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 2070, in fsCheck
  File "radiolog.py", line 2489, in fsParse
UnboundLocalError: local variable 'widget' referenced before assignment
135333:PARSING
135333:I110030181003018
135333: line:I110030181003018
135333:getCallsign called for FleetSync fleet=100 dev=3018
135333:  found matching entry/entries:[['100', '3018', 'Rescue 101']]
135333:FleetSync CID detected (not in $PKLSH): fleet=100  dev=3018  callsign=Rescue 101
135333:checking for existing open new entry tabs: callsign=Rescue 101 continueSec=20
135333:updating fsLog (fleetsync): fleet=100 dev=3018 callsign=<None>  COM port=COM3
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 2070, in fsCheck
  File "radiolog.py", line 2489, in fsParse
UnboundLocalError: local variable 'widget' referenced before assignment
135334:PARSING
135334:I110030181003018
135334: line:I110030181003018
135334:getCallsign called for FleetSync fleet=100 dev=3018
135334:  found matching entry/entries:[['100', '3018', 'Rescue 101']]
135334:FleetSync CID detected (not in $PKLSH): fleet=100  dev=3018  callsign=Rescue 101
135334:checking for existing open new entry tabs: callsign=Rescue 101 continueSec=20
135334:updating fsLog (fleetsync): fleet=100 dev=3018 callsign=<None>  COM port=COM3
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 2070, in fsCheck
  File "radiolog.py", line 2489, in fsParse
UnboundLocalError: local variable 'widget' referenced before assignment
135335:PARSING
135335:I110030181003018
135335: line:I110030181003018
135335:getCallsign called for FleetSync fleet=100 dev=3018
135335:  found matching entry/entries:[['100', '3018', 'Rescue 101']]
135335:FleetSync CID detected (not in $PKLSH): fleet=100  dev=3018  callsign=Rescue 101
135335:checking for existing open new entry tabs: callsign=Rescue 101 continueSec=20
135335:updating fsLog (fleetsync): fleet=100 dev=3018 callsign=<None>  COM port=COM3
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 2070, in fsCheck
  File "radiolog.py", line 2489, in fsParse
UnboundLocalError: local variable 'widget' referenced before assignment
135336:PARSING
135336:I110030181003018
135336: line:I110030181003018
135336:getCallsign called for FleetSync fleet=100 dev=3018
135336:  found matching entry/entries:[['100', '3018', 'Rescue 101']]
135336:FleetSync CID detected (not in $PKLSH): fleet=100  dev=3018  callsign=Rescue 101
135336:checking for existing open new entry tabs: callsign=Rescue 101 continueSec=20
135336:updating fsLog (fleetsync): fleet=100 dev=3018 callsign=<None>  COM port=COM3
Uncaught exception
Traceback (most recent call last):
  File "radiolog.py", line 2070, in fsCheck
  File "radiolog.py", line 2489, in fsParse
UnboundLocalError: local variable 'widget' referenced before assignment
```

**Comment by caver456** [comment]
This is in code added in Sept 2023 for #683; this whole clause was new in that branch.  Add a check to only run this clause if widget is defined.  Not sure how to reproduce the case where widget is not defined - basically, if newEntryWidget.instances is empty.  Regardless, this should catch that case.

```
		# 683 - activate the widget if needed here, rather than in addTab which only happens for new tabs
		# rprint('checking to see if widget should be activated: widget='+str(widget)+'  currentEntryLastModAge='+str(self.currentEntryLastModAge)+'  tab count='+str(self.newEntryWindow.ui.tabWidget.count()))
		#748 - only attempt this clause if widget is defined (i.e. if there was a find, or, the last widget in the list)
		if widget and (self.currentEntryLastModAge>holdSec or self.newEntryWindow.ui.tabWidget.count()==3):
			# rprint('  activating New Entry Widget: '+widget.ui.teamField.text())
			self.newEntryWindow.ui.tabWidget.setCurrentWidget(widget)
			widget.ui.messageField.setFocus()
```
